#!/bin/sh

add_to_hosts() {
    echo "$*" >> /etc/hosts
    echo "Added redirect: $2 > $1"
}

# iTunesStoreX's host file backup
if [ -e /etc/hosts.bak ]
then
    echo "iTunesStoreX's backup exists, reverting..."
    cp /etc/hosts.bak /etc/hosts
fi

# Store a backup
echo "Making a backup..."
cp /etc/hosts /etc/hosts.itunesstorexv.bak

add_to_hosts 76.217.61.232 phobos.apple.com
add_to_hosts 76.217.61.232 ax.init.itunes.apple.com
add_to_hosts 76.217.61.232 init.itunes.apple.com
